version: '3'

services:
  # Kafka service
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka_broker
    ports:
      - '9094:9094'
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller,broker 
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093 
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER 
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT 
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://127.0.0.1:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
    mem_limit: 512m
    mem_reservation: 128M
    cpus: 0.5

  # MongoDB service
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    mem_limit: 512m
    mem_reservation: 128M
    cpus: 0.5

  # Node.js service for API-gestion-db
  api_gestion_db:
    build: ./API-gestion-db/
    environment:
      - KAFKA_ADRESS=kafka:9092
      - KAFKA_ID=Consumer
      - MONGO_NETWORK=mongodb
      - MONGO_HOST=27017
    mem_limit: 512m
    mem_reservation: 128M
    cpus: 0.5

  # Node.js service for Serveur
  serveur:
    build: ./Serveur/
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - KAFKA_ADRESS=kafka:9092
      - KAFKA_ID=Serveur
    mem_limit: 512m
    mem_reservation: 128M
    cpus: 0.5

  # Python service for Shop
  shop:
    build: ./Shop/
    ports:
      - "8000:8000"
    mem_limit: 512m
    mem_reservation: 128M
    cpus: 0.5

  # Python service for ca
  ca:
    build: ./API-gestion-client/
    ports:
      - "50127:50127"
    mem_limit: 512m
    mem_reservation: 128M
    cpus: 0.5
    

volumes:
  mongodb_data:
