# Use an existing Node.js image as a base
FROM node:20-alpine3.17

# Create a working directory in the container
WORKDIR /API-gestion-db

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install application dependencies
RUN npm install

# Setting up ENV variable
ENV KAFKA_ADRESS 'localhost:9094'
ENV KAFKA_ID 'Consumer'

# Copy the rest of the application code to the working directory
COPY src ./src

# Command to start your application
CMD ["node", "src/index.js"]