# Use the official Python image as the base image
FROM python:3.9

# Set the working directory inside the container
WORKDIR /API-gestion-client

# Copy the requirements file to the working directory
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application code to the container
COPY . .

# Expose the port on which the application will run
EXPOSE 50127

# Command to run the application
CMD ["uvicorn", "ca-mongodb:app", "--host", "0.0.0.0", "--port", "50127"]
