# Use an existing Node.js image as a base
FROM node:20-alpine3.17

# Create a working directory in the container
WORKDIR /Serveur

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install application dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY src ./src

# Set a default value for the exposed port (you can override this during runtime)
ENV PORT 8080
ENV KAFKA_ADRESS 'localhost:9094'
ENV KAFKA_ID 'Serveur'

# Expose the port that the application will run on
EXPOSE $PORT

# Command to start your application
CMD ["node", "src/index.js"]