# Use an existing Node.js image as a base
FROM node:20-alpine3.17

# Create a working directory in the container
WORKDIR /Serveur

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install application dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY src ./src

# Expose the port that the application will run on
EXPOSE 8080

# Command to start your application
CMD ["node", "src/index.js"]